project_id = "cetccjtelascpdpvluod"

[functions.stripe-webhook]
verify_jwt = false

[functions.subscription-scheduler]
verify_jwt = false

[functions.check-promotion-limits]
verify_jwt = false

[functions.send-shipping-notification]
verify_jwt = true

[functions.send-guest-order-confirmation]
verify_jwt = false

[functions.auto-pause-subscription]
verify_jwt = false
