import { useState, useEffect } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Calendar } from '@/components/ui/calendar';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { CalendarIcon, Truck, Package, ExternalLink, RefreshCw, Send } from 'lucide-react';
import { format } from 'date-fns';
import { cn } from '@/lib/utils';
import { carrierOptions, shippingStatusOptions, generateTrackingUrl, isKnownCarrier } from '@/lib/carriers';

interface ShippingData {
  carrier: string | null;
  carrier_code: string | null;
  tracking_number: string | null;
  tracking_url: string | null;
  shipped_at: string | null;
  estimated_delivery_date: string | null;
  status: string;
}

interface ShippingTrackingFormProps {
  initialData: ShippingData;
  onSave: (data: Partial<ShippingData>) => Promise<void>;
  onMarkAsShipped: () => Promise<void>;
  onSendShippingEmail?: () => Promise<void>;
  loading?: boolean;
}

export const ShippingTrackingForm = ({
  initialData,
  onSave,
  onMarkAsShipped,
  onSendShippingEmail,
  loading = false,
}: ShippingTrackingFormProps) => {
  const [carrier, setCarrier] = useState(initialData.carrier || '');
  const [customCarrier, setCustomCarrier] = useState('');
  const [trackingNumber, setTrackingNumber] = useState(initialData.tracking_number || '');
  const [trackingUrl, setTrackingUrl] = useState(initialData.tracking_url || '');
  const [autoGeneratedUrl, setAutoGeneratedUrl] = useState<string | null>(null);
  const [shippedAt, setShippedAt] = useState<Date | undefined>(
    initialData.shipped_at ? new Date(initialData.shipped_at) : undefined
  );
  const [estimatedDelivery, setEstimatedDelivery] = useState<Date | undefined>(
    initialData.estimated_delivery_date ? new Date(initialData.estimated_delivery_date) : undefined
  );
  const [status, setStatus] = useState(initialData.status || 'pending');
  const [useCustomUrl, setUseCustomUrl] = useState(false);

  // Auto-generate tracking URL when carrier or tracking number changes
  useEffect(() => {
    const effectiveCarrier = carrier === 'OTHER' ? customCarrier : carrier;
    if (effectiveCarrier && trackingNumber) {
      const generated = generateTrackingUrl(effectiveCarrier, trackingNumber);
      setAutoGeneratedUrl(generated);
      
      // Auto-fill tracking URL if not using custom and we have a generated one
      if (!useCustomUrl && generated) {
        setTrackingUrl(generated);
      }
    } else {
      setAutoGeneratedUrl(null);
    }
  }, [carrier, customCarrier, trackingNumber, useCustomUrl]);

  const handleSave = async () => {
    const effectiveCarrier = carrier === 'OTHER' ? customCarrier : carrier;
    await onSave({
      carrier: effectiveCarrier || null,
      carrier_code: carrier.toLowerCase() || null,
      tracking_number: trackingNumber || null,
      tracking_url: trackingUrl || null,
      shipped_at: shippedAt?.toISOString() || null,
      estimated_delivery_date: estimatedDelivery?.toISOString().split('T')[0] || null,
      status,
    });
  };

  const handleMarkAsShipped = async () => {
    // Set shipped_at to now and status to shipped
    setShippedAt(new Date());
    setStatus('shipped');
    await onMarkAsShipped();
  };

  const currentStatus = shippingStatusOptions.find(s => s.value === status);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Truck className="h-5 w-5 text-primary" />
          <h3 className="font-semibold">Shipping & Tracking</h3>
        </div>
        {currentStatus && (
          <Badge variant="outline" className={cn(
            status === 'delivered' && 'bg-green-500/20 text-green-600 border-green-500/30',
            status === 'shipped' && 'bg-purple-500/20 text-purple-600 border-purple-500/30',
            status === 'in_transit' && 'bg-blue-500/20 text-blue-600 border-blue-500/30',
            status === 'pending' && 'bg-yellow-500/20 text-yellow-600 border-yellow-500/30',
            status === 'failed' && 'bg-red-500/20 text-red-600 border-red-500/30',
          )}>
            {currentStatus.label}
          </Badge>
        )}
      </div>

      <Separator />

      <div className="grid gap-4 md:grid-cols-2">
        {/* Carrier Selection */}
        <div className="space-y-2">
          <Label>Carrier</Label>
          <Select value={carrier} onValueChange={setCarrier}>
            <SelectTrigger>
              <SelectValue placeholder="Select carrier..." />
            </SelectTrigger>
            <SelectContent>
              {carrierOptions.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  {option.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {carrier === 'OTHER' && (
            <Input
              placeholder="Enter carrier name (e.g., Local Courier)"
              value={customCarrier}
              onChange={(e) => setCustomCarrier(e.target.value)}
              className="mt-2"
            />
          )}
        </div>

        {/* Tracking Number */}
        <div className="space-y-2">
          <Label>Tracking Number</Label>
          <Input
            placeholder="Enter tracking number"
            value={trackingNumber}
            onChange={(e) => setTrackingNumber(e.target.value)}
          />
        </div>

        {/* Tracking URL */}
        <div className="space-y-2 md:col-span-2">
          <div className="flex items-center justify-between">
            <Label>Tracking URL</Label>
            {autoGeneratedUrl && (
              <Button
                variant="ghost"
                size="sm"
                className="h-6 text-xs"
                onClick={() => {
                  setUseCustomUrl(false);
                  setTrackingUrl(autoGeneratedUrl);
                }}
              >
                <RefreshCw className="h-3 w-3 mr-1" />
                Auto-generate
              </Button>
            )}
          </div>
          <div className="flex gap-2">
            <Input
              placeholder={isKnownCarrier(carrier) ? "Auto-generated from carrier" : "Paste tracking URL manually"}
              value={trackingUrl}
              onChange={(e) => {
                setTrackingUrl(e.target.value);
                setUseCustomUrl(true);
              }}
              className="flex-1"
            />
            {trackingUrl && (
              <Button
                variant="outline"
                size="icon"
                asChild
              >
                <a href={trackingUrl} target="_blank" rel="noopener noreferrer">
                  <ExternalLink className="h-4 w-4" />
                </a>
              </Button>
            )}
          </div>
          {!isKnownCarrier(carrier) && carrier === 'OTHER' && (
            <p className="text-xs text-muted-foreground">
              Enter the full tracking URL for this carrier manually
            </p>
          )}
        </div>

        {/* Shipped At */}
        <div className="space-y-2">
          <Label>Shipped At</Label>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal",
                  !shippedAt && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4" />
                {shippedAt ? format(shippedAt, "PPP p") : "Not shipped yet"}
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0" align="start">
              <Calendar
                mode="single"
                selected={shippedAt}
                onSelect={setShippedAt}
                initialFocus
                className="pointer-events-auto"
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Estimated Delivery */}
        <div className="space-y-2">
          <Label>Estimated Delivery</Label>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant="outline"
                className={cn(
                  "w-full justify-start text-left font-normal",
                  !estimatedDelivery && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4" />
                {estimatedDelivery ? format(estimatedDelivery, "PPP") : "Set estimate"}
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0" align="start">
              <Calendar
                mode="single"
                selected={estimatedDelivery}
                onSelect={setEstimatedDelivery}
                initialFocus
                className="pointer-events-auto"
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Status */}
        <div className="space-y-2 md:col-span-2">
          <Label>Shipping Status</Label>
          <Select value={status} onValueChange={setStatus}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {shippingStatusOptions.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  <div className="flex flex-col">
                    <span>{option.label}</span>
                    <span className="text-xs text-muted-foreground">{option.description}</span>
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      <Separator />

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-2">
        <Button onClick={handleSave} disabled={loading}>
          <Package className="h-4 w-4 mr-2" />
          Save Tracking Info
        </Button>
        
        {status !== 'shipped' && status !== 'delivered' && status !== 'in_transit' && (
          <Button
            variant="secondary"
            onClick={handleMarkAsShipped}
            disabled={loading || !trackingNumber}
          >
            <Truck className="h-4 w-4 mr-2" />
            Mark as Shipped
          </Button>
        )}

        {onSendShippingEmail && trackingNumber && (
          <Button
            variant="outline"
            onClick={onSendShippingEmail}
            disabled={loading}
          >
            <Send className="h-4 w-4 mr-2" />
            Send Shipping Email
          </Button>
        )}
      </div>
    </div>
  );
};