// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.77.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List coffee products",
  description: "Browse the Habesha coffee catalog, optionally filtered by category or search text.",
  inputSchema: {
    search: z.string().trim().optional().describe("Text to match against product names."),
    category: z.string().trim().optional().describe("Category filter, e.g. 'Single Origin'."),
    limit: z.number().int().optional().describe("Maximum number of products to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("products").select("id, name, description, price, category, in_stock, stock_quantity").order("display_order", { ascending: true }).limit(Math.min(Math.max(limit ?? 20, 1), 50));
    if (search) query = query.ilike("name", `%${search}%`);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_orders_default = defineTool2({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in customer's recent orders with status and totals.",
  inputSchema: {
    status: z2.string().trim().optional().describe("Optional order status filter, e.g. 'shipped'."),
    limit: z2.number().int().optional().describe("Maximum number of orders to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("orders").select("id, order_number, status, total, carrier, tracking_number, tracking_url, estimated_delivery_date, created_at").order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 10, 1), 50));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool3, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var get_order_default = defineTool3({
  name: "get_order",
  title: "Get order details",
  description: "Get one of the signed-in customer's orders, including line items and shipment tracking.",
  inputSchema: {
    order_number: z3.string().trim().min(1).describe("The order number, as shown in order history.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: order, error } = await supabase.from("orders").select("id, order_number, status, subtotal, tax, shipping, total, carrier, tracking_number, tracking_url, shipped_at, delivered_at, estimated_delivery_date, created_at").eq("order_number", order_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!order) throw new ToolError(`No order found with number ${order_number}`);
    const { data: items, error: itemsError } = await supabase.from("order_items").select("product_name, quantity, unit_price, total_price").eq("order_id", order.id);
    if (itemsError) return { content: [{ type: "text", text: itemsError.message }], isError: true };
    const payload = { ...order, items: items ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: { order: payload }
    };
  }
});

// src/lib/mcp/tools/list-my-subscriptions.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_my_subscriptions_default = defineTool4({
  name: "list_my_subscriptions",
  title: "List my coffee subscriptions",
  description: "List the signed-in customer's coffee subscriptions with status, cadence and next delivery date.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("subscriptions").select("id, status, product_name, frequency, quantity, grind, bag_size, price, next_delivery_date, paused_at, resume_at, cancelled_at, created_at").order("created_at", { ascending: false }).limit(25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { subscriptions: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cetccjtelascpdpvluod";
var mcp_default = defineMcp({
  name: "habesha-coffee-brew",
  title: "habesha-coffee-brew",
  version: "0.1.0",
  instructions: "Tools for the Habesha Coffee store. Browse the coffee catalog, and look up the signed-in customer's orders, order tracking and coffee subscriptions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, list_my_orders_default, get_order_default, list_my_subscriptions_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
